### PR TITLE
RAD-177: Update Makefile

### PR DESCRIPTION
**Pull request by rsinnet**
Add the help goal and update some of the other goals. Also add a
prologue and set some sane defaults.

### CODE REVIEW

**Review by ludwig — APPROVED** [review]

**Review by ppbrown — COMMENTED** [review]
Seems like you made three levels of changes:

1. added environment setting of DOCKER_BUILDKIT. great

2. changed names of variables. erm... i dunno

3. broke convention on Makefile variable naming, by changing UPPERCASE var names, to lowercase?

As a long-time makefile user, I strongly perfer sticking to the standard Makefile "vars should be uppercase"  naming convention there.

**Comment by rsinnet** [comment]
> Seems like you made three levels of changes:
> 
> 1. added environment setting of DOCKER_BUILDKIT. great
> 2. changed names of variables. erm... i dunno
> 3. broke convention on Makefile variable naming, by changing UPPERCASE var names, to lowercase?
> 
> As a long-time makefile user, I strongly perfer sticking to the standard Makefile "vars should be uppercase" naming convention there.

For 2, if you look through our codebase, you will find a much higher occurrence of these variable names that I changed to. I'm changing this to reflect that.

As for 3, what conventions are you talking about? I found this style guide:
https://style-guides.readthedocs.io/en/latest/makefile.html

Also, in the GNU Make reference manual, the variables section uses lowercase: https://www.gnu.org/software/make/manual/make.html#Reference

I think the reason that lowercase variables are the standard is because then you don't accidentally overwrite a built-in variable. Same thing with shell parameters in Bash according to the GNU Bash manual: https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameters

**Comment by ppbrown** [comment]
Arg. I hate it when standards change :-/
I was going by how I learned (standard, not GNU) Makefile syntax at UC Berkeley 30 years ago, and saw in every makefile I touched 10-15 years after that.
Makefile variables were always uppercase.
Then, when you had to use shell variables in makefile targets, 
(eg: inline "for x in ...." clauses and the like)
you used lowercase.  So in the makefile, lowercase vars were shell, uppercase was make.

But, seems like that is not the general practice any more, so I withdraw my comment

**Comment by rsinnet** [comment]
> Arg. I hate it when standards change :-/ I was going by how I learned (standard, not GNU) Makefile syntax at UC Berkeley 30 years ago, and saw in every makefile I touched 10-15 years after that. Makefile variables were always uppercase. Then, when you had to use shell variables in makefile targets, (eg: inline "for x in ...." clauses and the like) you used lowercase. So in the makefile, lowercase vars were shell, uppercase was make.
> 
> But, seems like that is not the general practice any more, so I withdraw my comment

You probably won't be surprised to hear that I learned it the same way as you LOL but I read some of these manuals in the last few years.

**Review by staheri — APPROVED** [review]

**Pull request merged**
